#
# Copyright (C) 2014 Lab Mouse Security
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

CC=cc
RM=rm
BIN=crush
MAKE=make
CFLAGS=-pipe -fpie -pedantic -O2 -W -Werror -Wno-long-long -I../include
LFLAGS=-pie
SHELL = /bin/sh
